### ISSUE TITLE
Clicking a checkbox label doesn't check the box

### ISSUE THREAD

**Issue by bmesuere** [ebi-uniprot/biojs-vis-proteinFeaturesViewer#6]
The checkboxes in the settings dialog and filtering don't respond to clicks on the label.
This can be fixed by wrapping the labels around the input tag, or by setting the `for` attribute of the label.

The smallest change to fix this is by adding `.attr('for', filter.id)` after https://github.com/ebi-uniprot/biojs-vis-proteinFeaturesViewer/blob/master/lib/VariantFilterDialog.js#L80.

**Comment by ljgarcia** [comment]
Done. We also add some lighter/darker effect plus cursor pointer to highlight the actionable elements.
