### ISSUE TITLE
Scrolling performance

### ISSUE THREAD

**Issue by bmesuere** [ebi-uniprot/biojs-vis-proteinFeaturesViewer#7]
Hi,

While playing with the (very nice) new viewer, I noticed that scrolling was not buttery smooth. Instead of continuing to write my PhD thesis tonight, I had some fun with chrome dev tools.

While scrolling, the calculations needed for each frame often take over 100ms (on a fast macbook pro) resulting in an average frame rate of about 5fps.

Profiling using the chrome dev tools reveals that there are 2 main causes, each containing many nodes: the AA-bar and the variants.
(Switching to a single text element for all of the AAs, using letter spacing would probably the best performance improvement, but getting the letters in exactly the right position is probably too hard)

**SetAttribute**
When we dig deeper, the profiler reveals that each frame, 10ms are spent on `setAttribute`. Many of those are attributes that are set again, but never change, for example at https://github.com/ebi-uniprot/biojs-vis-proteinFeaturesViewer/blob/master/lib/FeaturesViewer.js#L309

Moving the stable attributes to the `enter()` saves a few ms each frame:

```javascript
aminoAcids.enter()
    .append('text')
    .style('text-anchor','middle')
    .attr('y', aaViewHeight / 2) // assuming aaViewHeight can't change
    .text(function(d) {
        return d.toUpperCase();
    })
    .attr('title', function(d, i) {
        return (i+1);
    })
    .attr('class','up_pftv_amino-acid');
aminoAcids
    .attr('x', function(d, i) {
        return fv.xScale(i+1);
    });
```

The same is true for the [variant circles](https://github.com/ebi-uniprot/biojs-vis-proteinFeaturesViewer/blob/master/lib/VariantViewer.js#L71) and [shapes](https://github.com/ebi-uniprot/biojs-vis-proteinFeaturesViewer/blob/master/lib/BasicViewer.js#L27).

**Updating the hidden AA bar**
If the AA bar is hidden, we can skip the position recalculation. This not only saves a few ms in *scripting*, but also in *style recalculation* and *layout*.
```javascript
aaViewer.update = function() {
    gAxis.call(xAxis);
    selectorGroup.call(selectorSeries);
    var count = fv.xScale.domain()[1] - fv.xScale.domain()[0];
    if (count > 70) {
        g.transition(50).style('opacity',0);
    } else {
        g.call(series);
        g.transition(50).style('opacity',1);
    }
};
```
Note that there's a small drawback to this, the letters won't move anymore while they fade out.

**addEventsClassAndTitle**
After the previous issues are fixed, adding event listeners in `addEventsClassAndTitle` is the most expensive operation. Similar to the first issue, it seems that the listeners are added again and again on each update/scroll event. Only passing the new shapes to this function will take care of this:

```javascript
var newShapes = shapes.enter().append('path')
    .attr('name', function (d) {
        return d.internalId;
    }).attr('class', function (d) {
        return 'up_pftv_feature up_pftv_' + d.type.name.toLowerCase();
    });

shapes
    .attr('d', function (d) {
        return FeatureFactory.getFeature(
            d.type.name,
            fv.xScale(2) - fv.xScale(1),
            layout.getFeatureHeight(),
            (d.end) ? d.end - d.begin + 1 : 1);
    })

.attr('transform', function (d) {
    return 'translate(' + fv.xScale(d.begin) + ',' + layout.getYPos(d) + ')';
})

;
ViewerHelper.addEventsClassAndTitle(catTitle, newShapes, fv, container);
```
The same change can be made for the variants.

**Results**
:tada: We got rid of the costly style recalculations and layouts + some of the scripting. After these changes, the time needed per frame dropped to 20-30ms resulting in 30+fps. Still not perfect, but noticeably better. To get to 60fps, you probably need an efficient way to check if a node is visible or not and only calculate/update its attributes when it is.

Cheers,
Bart from Unipept

**Comment by bmesuere** [comment]
As a bonus, panning speed increased from 10fps to 30-45fps!

**Comment by xwatkins** [comment]
Thanks Bart, that is extremely useful!! Might get you to help me with profiling if you're ever round at the EBI.

**Comment by bmesuere** [comment]
No problem! If you have any further questions, let me know!

**Comment by ljgarcia** [comment]
Thanks so much for your time and comments! We have now implemented your suggestions. We will see what else we can improve. Thanks again!
